jwt:
  key: 45k3kofmweaofaetogetyeeahaehksdfgnp;4o0p-ttgk09r034g3k4gbosfk0320
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: testdb
      username: admin
      password: admin

